### ISSUE TITLE
Possible to use without ThrowPropsPlugin?

### ISSUE THREAD

**Issue by zachharkey** [kitajchuk/grunt-nautilus-squarespace-boilerplate#1]
First, thanks for sharing all this hard work. I've been following along the instructions in the excellent Readme but I ran into some problems with the greensock-js.

> Running "nautilus:build" (nautilus) task
> Fatal error: Could not locate import `` found in `js/app/gs-draggable.js`

Is it possible to use this boilerplate without the ThrowPropsPlugin? I downloaded public greensock-js and put it in my root as greensock-js. However I don't have a developer license to use the ThrowPropsPlugin, (yet). 

I was able to get the grunt tasks to execute by commenting out line 3 of `js/app/gs-draggable.js` but I'm not familiar with this plugin and I'm still trying to wrap my head around this build process so I don't know if that is a workable solution.

Is the ThrowPropsPlugin a dealbreaker for using this boilerplate?

**Comment by kitajchuk** [comment]
Yeah but you would just have to exclude it from the imports. It's kind of a bootstrap, not meant to be set in stone or anything.

**Comment by kitajchuk** [comment]
You can remove the dependency here: https://github.com/kitajchuk/grunt-nautilus-squarespace-boilerplate/blob/master/js/app/galleries/slider.js#L18

And rather than perform the dependency script load here, just perform your modules onload methods: https://github.com/kitajchuk/grunt-nautilus-squarespace-boilerplate/blob/master/js/app/galleries/slider.js#L63

**Comment by kitajchuk** [comment]
You could replicate the basic dragging with Hammerjs's pan events, that's not too tough. We've done it on a number of projects but they're all Private repositories so I can't link out to source. The physics would be tough though :/ That's why ThrowPropsPlugin is so nice but you do have to pay for a GS membership to get that one :/
