### ISSUE TITLE
ProperJS deprecated

### ISSUE THREAD

**Issue by mwickett** [kitajchuk/grunt-nautilus-squarespace-boilerplate#2]
You're likely aware, but got this when running `npm install`:

````
npm WARN deprecated properjs@0.5.1: ProperJS has switched to using CommonJS and standard npm dependency format.
npm WARN deprecated properjs-raf@0.1.3: ProperJS has switched to using CommonJS and standard npm dependency format.
````

Thanks for all you create for the community around Squarespace - amazing stuff!

**Comment by kitajchuk** [comment]
Yes! I updated the entire [ProperJS](https://github.com/ProperJS) code-base. The boilerplate was using the older version that implemented the properjs-cli and bundler. I deprecated several modules on npm since they will no longer be maintained. The good news is that if you want to keep using this, the bundle module and the CLI still work and use all modules at their versions prior to the CommonJS switch.

I have been refining my own process, so moving forward I will be creating another boiler-plate. This one will not use [Grunt Nautilus](https://github.com/kitajchuk/grunt-nautilus) and will be more of an open-ended blank slate starting point. I have a current, in-progress, Squarespace site using this process that is a direct port from this boiler-plate to an updated workflow.

The gist of the new process looks like this:

- Webpack for module dependency
- Bable for ES6 integration
- ESLint for code linting
- SASS + PostCSS + Autoprefixer
- npm-scripts for task management
